In [1]:
from pandas import Series, DataFrame

In [19]:
import pandas as pd
import numpy as np

In [4]:
obj = Series([4, -7, -5, 3])

In [5]:
obj

0    4
1   -7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4, -7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2['a']

-5

In [14]:
obj2['d']

4

In [15]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [16]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [17]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [20]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

##### 通过传递字典来创建一个Series 

In [23]:
sdata = {'ohio' : 3500, 'Texas' : 71000, 'Oregen' : 16000, 'Utah' : 5000}

In [24]:
obj3 = Series(sdata)

In [25]:
obj3

Oregen    16000
Texas     71000
Utah       5000
ohio       3500
dtype: int64

In [32]:
states = ['California', 'ohio', 'Oregen']

In [33]:
obj4 = Series(sdata, index = states)

In [34]:
obj4

California        NaN
ohio           3500.0
Oregen        16000.0
dtype: float64

In [35]:
pd.isnull(obj4)

California     True
ohio          False
Oregen        False
dtype: bool

In [36]:
pd.notnull(obj4)

California    False
ohio           True
Oregen         True
dtype: bool

In [37]:
obj4.isnull()

California     True
ohio          False
Oregen        False
dtype: bool

In [38]:
obj3

Oregen    16000
Texas     71000
Utah       5000
ohio       3500
dtype: int64

In [41]:
obj4

California        NaN
ohio           3500.0
Oregen        16000.0
dtype: float64

#### Series会自动对齐不同索引的数据

In [40]:
obj3 + obj4

California        NaN
Oregen        32000.0
Texas             NaN
Utah              NaN
ohio           7000.0
dtype: float64

#### Series对象本省和它的索引都有一个那么值

In [42]:
obj4.name = 'population'

In [43]:
obj4.index.name = 'state'

In [44]:
obj4

state
California        NaN
ohio           3500.0
Oregen        16000.0
Name: population, dtype: float64

In [45]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [46]:
obj

Bob      4
Steve   -7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame
#### 表示一个表格，它可以被看作是一个Series的字典（每个Series共享一个索引）

In [47]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [48]:
frame = DataFrame(data)

In [49]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [50]:
DataFrame(data, columns = ['year','state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [54]:
frame2 = DataFrame(data, columns = ['year','state', 'pop','debt'])

In [55]:
frame2.index = ['one', 'two', 'three', 'four', 'five']

In [56]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [57]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [58]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [59]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [60]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [61]:
frame2['debt'] = 16.5

In [62]:
frame2['debt']

one      16.5
two      16.5
three    16.5
four     16.5
five     16.5
Name: debt, dtype: float64

## 嵌套的字典的字典
### 如果被传递到DataFrame，它的外键被解释为列索引，内部键被解释为行索引

In [64]:
pop = {
    'Nevada' : {2001:2.4, 2002: 2.9},
    'Ohio' : {2000 : 1.5, 2001 : 1.7, 2002 : 3.6}
}

In [65]:
frame3 = DataFrame(pop)

In [66]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [68]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [69]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [70]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [80]:
pdata = {
    'Ohio' : frame3['Ohio'][:-1],
    'Nevada': frame3['Nevada'][:-1]
}

In [81]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [82]:
frame3.index.name='year'

In [83]:
frame3.columns.name='state'

In [84]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [85]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [86]:
frame2.values

array([[2000, 'Ohio', 1.5, 16.5],
       [2001, 'Ohio', 1.7, 16.5],
       [2002, 'Ohio', 3.6, 16.5],
       [2001, 'Nevada', 2.4, 16.5],
       [2002, 'Nevada', 2.9, 16.5]], dtype=object)